# Generated by Django 4.1.2 on 2022-10-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
