# Generated by Django 4.1.2 on 2022-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.PositiveBigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
