# Generated by Django 4.1.2 on 2022-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_current_price_alter_listing_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.URLField(),
        ),
    ]
